### ISSUE TITLE
render_nerf.py script is missing

### ISSUE THREAD

**Issue by sam598** [JamesPerlman/TurboNeRF-Blender#5]
Link in the readme currently leads to a 404

**Comment by nokel** [comment]
Still relevant, can't find script either...

**Comment by sam598** [comment]
I talked the developer on twitch and it sounds like it won't get updated.

But NerfStudio now has a Blender add-on that is quite good. NerfStudio supports instant-ngp, and nerfacto is a fantastic balance of speed and quality.
https://docs.nerf.studio/en/latest/quickstart/blender_addon.html
