### ISSUE TITLE
No module named 'pyngp'

### ISSUE THREAD

**Issue by McCaffeteria** [JamesPerlman/TurboNeRF-Blender#6]
This is almost certainly not a problem with the actual addon, but I'm not sure where else to ask about it.

When trying to activate the addon blender is giving an error when ngp_testbed_manager.py is trying to import pyngp, saying "ModuleNotFoundError: No module named 'pyngp.'" This error is listed in the original [NVlabs instant-ngp github](https://github.com/NVlabs/instant-ngp#:~:text=Python%20error%3A%20No%20module%20named%20%27pyngp%27) but I'm not sure whether their suggestion is even applicable to blender's internal version of python.

instant-ngp runs just fine for me outside of blender. I've downloaded the instant-ngp repo, built it with cmake, and generated a few NeRFs. It seems to work fine. NVlabs [links to a thread](https://github.com/NVlabs/instant-ngp/issues/43#:~:text=the%20error%20you%20are%20seeing%20is%20basically%20that%20python%20cannot%20find%20these%20files%20in%20your%20path) where someone says that basically, the reason this error happens is that python can't find the files within the instant-ngp/build folder because they aren't explicitly added to your system path. I don't see them in my system path environment variables though and like I said, instant-ngp works. Blender also apparently has its own completely separate python environment anyway and doesn't even use the user's system path at all, so I'm kind of at a loss.

Am I supposed to be doing something in blender before adding the addon? Am I supposed to rebuild instant-ngp again within blender's environment? How am I even supposed to do that?

Thanks in advance for any help.

**Comment by JamesPerlman** [comment]
Hey!  If you're using the `revamp` branch - be warned that it's very broken right now.  I'm actively working on fixing it.  If you want to try to get it working, you'll have to rebuild instant-ngp with Blender's version of python, and then change the `NGP_DIR` in this file here: https://github.com/JamesPerlman/blender_nerf_tools/blob/revamp/utility/load_ngp.py to point to your `instant-ngp/build` directory.  I would not recommend using the `revamp` branch at all right now as it's going to be incompatible with a vanilla install of `instant-ngp`

**Comment by McCaffeteria** [comment]
I was trying to use the revamp branch. It didn't occur to me that this had anything to do with revamp being broken since the module it couldn't find is one that instant-ngp uses regardless.
Are you saying that the main branch doesn't have this problem? Or do I have to rebuild instant-ngp for blender in either case?

**Comment by hugosbnarciso** [comment]
hi, i'm having the same issue, did you find a solution?

**Comment by bergers1** [comment]
I'm using the main branch of InstantNGP, but i still get the same "ModuleNotFoundError: No module named 'pyngp.'"

**Comment by JamesPerlman** [comment]
Hey everyone - just an update for you here, I've been working on a new NeRF renderer which is fine-tuned to work with this repo.  The blender addon is now under active development and I'm closing in on a release, hopefully only a few weeks!

https://github.com/JamesPerlman/NeRFRenderCore
