### ISSUE TITLE
Module name: Typo in README.md

### ISSUE THREAD

**Issue by alechk4** [JamesPerlman/TurboNeRF-Blender#7]
0. Installation

When you download this addon, it will automatically be named something like blender_nerf_tools-master - you will need to rename this to ~~instant_ngp_tools~~ **blender_nerf_tools** before moving it to your addons folder. Will fix this soon!

**Comment by JamesPerlman** [comment]
Good catch.  I will certainly make sure the new installation instructions are verified before the next release!
