### ISSUE TITLE
Feature request: Export JSON camera path

### ISSUE THREAD

**Issue by alechk4** [JamesPerlman/TurboNeRF-Blender#9]
Using a camera path with `--video_camera_path` should be preferred over `--screenshot_transforms` as the former will (supposedly) use motion blur.
It would be nice to have an exporter for the camera path format instead of screenshot transforms. Probably it's only a matter of mapping the rotation matrices to quaternions, and changing the dict keys.

**Comment by JamesPerlman** [comment]
Good catch - in my early evaluation of `instant-ngp` i started using the screenshot transforms to render.  There is an undocumented render script here that uses this format.  https://github.com/JamesPerlman/nerf_utils
